# Generated by Django 2.0.8 on 2019-01-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteCount', models.IntegerField()),
                ('winCount', models.IntegerField()),
                ('code', models.TextField()),
                ('winRate', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
