# Generated by Django 2.1.4 on 2019-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='winRate',
            field=models.FloatField(),
        ),
    ]
