# Generated by Django 2.0.10 on 2019-04-29 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_auto_20190419_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='voteCount',
            new_name='vote_count',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='winCount',
            new_name='win_count',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='winRate',
            new_name='win_rate',
        ),
        migrations.AddField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
